
spring:
  profiles:
    active: pree1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    date-format: yyyy-MM-dd
  resources:
    static-locations: file:D://upload/
  #最大文件大小。值可以使用后缀“MB”或“KB”。指示兆字节或千字节大小。
  # 最大请求大小可以是mb也可以是kb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mybatis :
    mapper-locations : classpath:dao/*.xml

    config-location : classpath:mybatis-config.xml